services:
  postgres:
    image: postgres:16-alpine
    container_name: bankcore-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: BankCoreDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - bankcore-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d BankCoreDb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  bankcore-pg-data:
